export const ADD_CART = "addCart"
export const SELECT_ALL = "selectAll"
export const ADD_PRODUCT = "addProduct"
export const DECRE_PRODUCT = "decreProduct"
export const DECRE_PRODUCTS = "decreProducts"
export const CLEARALL = "clearAll"
export const CHECk = "toggleChecck"
export const UPDATELIST = "updateList"
export const DELETMUL = "deletAllSelec"

